BARCODES_A = {
    'A01': 'ACAACC',
    'A02': 'ACTCAC',
    'A03': 'AGGATG',
    'A04': 'ATCGAC',
    'A05': 'CAAGAG',
    'A06': 'CATGAC',
    'A07': 'CCTTCG',
    'A08': 'CGGTAG',
    'A09': 'CTATTG',
    'A10': 'CTCAGC',
    'A11': 'GCATTC',
    'A12': 'GTGAGG',
    'B01': 'GTTGAG',
    'B02': 'TATCTC',
    'B03': 'TCTCTG',
    'B04': 'TGACAG',
    'B05': 'TGCTGC',
    'B06': 'ACAGAC',
    'B07': 'AGAAGG',
    'B08': 'ATCAAG',
    'B09': 'CCATAG',
    'B10': 'GAAGTC',
    'B11': 'GGTAAC',
    'B12': 'TGTAGG'
}

BARCODES_B = {
    'C01': 'ACAACC',
    'C02': 'ACTCAC',
    'C03': 'AGGATG',
    'C04': 'ATCGAC',
    'C05': 'CAAGAG',
    'C06': 'CATGAC',
    'C07': 'CCTTCG',
    'C08': 'CGGTAG',
    'C09': 'CTATTG',
    'C10': 'CTCAGC',
    'C11': 'GCATTC',
    'C12': 'GTGAGG',
    'D01': 'GTTGAG',
    'D02': 'TATCTC',
    'D03': 'TCTCTG',
    'D04': 'TGACAG',
    'D05': 'TGCTGC',
    'D06': 'ACAGAC',
    'D07': 'AGAAGG',
    'D08': 'ATCAAG',
    'D09': 'CCATAG',
    'D10': 'GAAGTC',
    'D11': 'GGTAAC',
    'D12': 'TGTAGG',
}

BARCODES_C = {
    'E01': 'ACAACC',
    'E02': 'ACTCAC',
    'E03': 'AGGATG',
    'E04': 'ATCGAC',
    'E05': 'CAAGAG',
    'E06': 'CATGAC',
    'E07': 'CCTTCG',
    'E08': 'CGGTAG',
    'E09': 'CTATTG',
    'E10': 'CTCAGC',
    'E11': 'GCATTC',
    'E12': 'GTGAGG',
    'F01': 'GTTGAG',
    'F02': 'TATCTC',
    'F03': 'TCTCTG',
    'F04': 'TGACAG',
    'F05': 'TGCTGC',
    'F06': 'ACAGAC',
    'F07': 'AGAAGG',
    'F08': 'ATCAAG',
    'F09': 'CCATAG',
    'F10': 'GAAGTC',
    'F11': 'GGTAAC',
    'F12': 'TGTAGG',
}

BARCODES_D = {
    'G01': 'ACAACC',
    'G02': 'ACTCAC',
    'G03': 'AGGATG',
    'G04': 'ATCGAC',
    'G05': 'CAAGAG',
    'G06': 'CATGAC',
    'G07': 'CCTTCG',
    'G08': 'CGGTAG',
    'G09': 'CTATTG',
    'G10': 'CTCAGC',
    'G11': 'GCATTC',
    'G12': 'GTGAGG',
    'H01': 'GTTGAG',
    'H02': 'TATCTC',
    'H03': 'TCTCTG',
    'H04': 'TGACAG',
    'H05': 'TGCTGC',
    'H06': 'ACAGAC',
    'H07': 'AGAAGG',
    'H08': 'ATCAAG',
    'H09': 'CCATAG',
    'H10': 'GAAGTC',
    'H11': 'GGTAAC',
    'H12': 'TGTAGG',
}
