BARCODES_A = {
    'A1': 'ACAACC',
    'A2': 'ACTCAC',
    'A3': 'AGGATG',
    'A4': 'ATCGAC',
    'A5': 'CAAGAG',
    'A6': 'CATGAC',
    'A7': 'CCTTCG',
    'A8': 'CGGTAG',
    'A9': 'CTATTG',
    'A10': 'CTCAGC',
    'A11': 'GCATTC',
    'A12': 'GTGAGG',
    'B1': 'GTTGAG',
    'B2': 'TATCTC',
    'B3': 'TCTCTG',
    'B4': 'TGACAG',
    'B5': 'TGCTGC',
    'B6': 'ACAGAC',
    'B7': 'AGAAGG',
    'B8': 'ATCAAG',
    'B9': 'CCATAG',
    'B10': 'GAAGTC',
    'B11': 'GGTAAC',
    'B12': 'TGTAGG'
}

BARCODES_B = {
    'C1': 'ACAACC',
    'C2': 'ACTCAC',
    'C3': 'AGGATG',
    'C4': 'ATCGAC',
    'C5': 'CAAGAG',
    'C6': 'CATGAC',
    'C7': 'CCTTCG',
    'C8': 'CGGTAG',
    'C9': 'CTATTG',
    'C10': 'CTCAGC',
    'C11': 'GCATTC',
    'C12': 'GTGAGG',
    'D1': 'GTTGAG',
    'D2': 'TATCTC',
    'D3': 'TCTCTG',
    'D4': 'TGACAG',
    'D5': 'TGCTGC',
    'D6': 'ACAGAC',
    'D7': 'AGAAGG',
    'D8': 'ATCAAG',
    'D9': 'CCATAG',
    'D10': 'GAAGTC',
    'D11': 'GGTAAC',
    'D12': 'TGTAGG',
}

BARCODES_C = {
    'E1': 'ACAACC',
    'E2': 'ACTCAC',
    'E3': 'AGGATG',
    'E4': 'ATCGAC',
    'E5': 'CAAGAG',
    'E6': 'CATGAC',
    'E7': 'CCTTCG',
    'E8': 'CGGTAG',
    'E9': 'CTATTG',
    'E10': 'CTCAGC',
    'E11': 'GCATTC',
    'E12': 'GTGAGG',
    'F1': 'GTTGAG',
    'F2': 'TATCTC',
    'F3': 'TCTCTG',
    'F4': 'TGACAG',
    'F5': 'TGCTGC',
    'F6': 'ACAGAC',
    'F7': 'AGAAGG',
    'F8': 'ATCAAG',
    'F9': 'CCATAG',
    'F10': 'GAAGTC',
    'F11': 'GGTAAC',
    'F12': 'TGTAGG',
}

BARCODES_D = {
    'G1': 'ACAACC',
    'G2': 'ACTCAC',
    'G3': 'AGGATG',
    'G4': 'ATCGAC',
    'G5': 'CAAGAG',
    'G6': 'CATGAC',
    'G7': 'CCTTCG',
    'G8': 'CGGTAG',
    'G9': 'CTATTG',
    'G10': 'CTCAGC',
    'G11': 'GCATTC',
    'G12': 'GTGAGG',
    'H1': 'GTTGAG',
    'H2': 'TATCTC',
    'H3': 'TCTCTG',
    'H4': 'TGACAG',
    'H5': 'TGCTGC',
    'H6': 'ACAGAC',
    'H7': 'AGAAGG',
    'H8': 'ATCAAG',
    'H9': 'CCATAG',
    'H10': 'GAAGTC',
    'H11': 'GGTAAC',
    'H12': 'TGTAGG',
}
